version: '2.0'
     
services:
   
  cas-server-overlay:
    build: cas-server/cas-server-overlay
    image: cas-server-overlay:latest
    container_name: cnt-cas-server-overlay 
    ports:
      - 8443:8443
      - 8080:8080
    volumes:
      - ./cas-server/cas-server-overlay/etc/cas:/etc/cas
      
  
  cas-client-apache2:
    build: cas-clients-examples/cas-client-apache2
    image: cas-client-apache2:latest
    container_name: cnt-cas-client-apache2
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./cas-clients-examples/cas-client-apache2/src:/var/www/html/
      
      
 