version: '2.0'
     
services:
   
  cas-server-overlay:
    build: cas-server/cas-server-overlay
    image: cas-server-overlay:latest
    container_name: cnt-cas-server-overlay 
    ports:
      - 8443:8443
      - 8080:8080
    volumes:
      - ./cas-server/cas-server-overlay/etc/cas:/etc/cas
      
  
  cas-client-apache2:
    build: cas-clients-examples/cas-client-apache2
    image: cas-client-apache2:latest
    container_name: cnt-cas-client-apache2
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./cas-clients-examples/cas-client-apache2/src:/var/www/html/
      
  cas-secured-app-one:
    build: cas-clients-examples/cas-secured-app-one
    image: cas-secured-app-one:latest
    container_name: cnt-cas-secured-app-one
    ports:
      - 9001:9001
      
  saml-secured-app-one:
    build: cas-clients-examples/saml-secured-app-one
    image: saml-secured-app-one:latest
    container_name: cnt-saml-secured-app-one
    ports:
      - 9002:9002
  
  saml-client-shibboleth-sp:
    build: cas-clients-examples/saml-client-shibboleth-sp
    image: saml-client-shibboleth-sp:latest
    container_name: cnt-saml-client-shibboleth-sp
    ports:
      - 443:443
      - 80:80
  