openapi: "3.0.0"
info:
  description: "billboard service: Another pet project"
  version: "0.1.0-SNAPSHOT"
  title: "Billboard service"
  contact:
    email: "rodrigo.villamil@gmail.com"
tags:
  - name: "show"
    description: "Operations about showsd"
servers:
  - url: http://localhost:8080/
    description: "Servidor localhost"
paths:
  /shows/{id}:
    get:
      tags:
        - "show"
      summary: "Retrieves show by ID"
      operationId: "getShowById"
      parameters:
        - name: "id"
          in: "path"
          description: "Id of show to return"
          required: true
          schema:
            type: "integer"
            format: "int64"
      responses:
        '200':
          description: "Retrieves one show by id"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Show'
        '404':
          description: "Show not found"
          content: {}
  /shows:
    post:
      tags:
      - "show"
      summary: "Create a new show"
      operationId: addShow
      requestBody:
        description: Show oject that needs to be added to the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Show'
          application/xml:
            schema:
              $ref: '#/components/schemas/Show'
        required: true
      responses:
        405:
          description: Invalid input
          content: {}      
      x-codegen-request-body-name: body      
    get:
      tags:
      - "show"
      summary: "Retrieves all shows"
      operationId: "getAllShows"
      responses:
        '200':
          description: "Retrieves all shows"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfShow'
components:
  schemas:
    Show:
      type: "object"
      required:        
        - "title"
      properties:        
        title:
          type: "string"
          example: "Batman"
          description: "Original title"
        year:
          type: "string"
          example: "1979"
        imdbScore:
          type: "string"
          example: "7.5"
          description: "Score on IMDB"
          
    ArrayOfShow:
      type: array
      items:
        $ref: '#/components/schemas/Show'  