
CREATE TABLE IF NOT EXISTS `SHOW_ENTITY` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `TITLE` varchar(255) DEFAULT NULL,
  `YEAR`  char(4) DEFAULT NULL,
  `IMDB_SCORE` char(5) DEFAULT NULL,
  PRIMARY KEY(id)
);
