INSERT INTO SHOW_ENTITY (TITLE, YEAR, IMDB_SCORE) VALUES('Superman','1976','8.4');
INSERT INTO SHOW_ENTITY (TITLE, YEAR, IMDB_SCORE) VALUES('Batman','1997','8.5');
INSERT INTO SHOW_ENTITY (TITLE, YEAR, IMDB_SCORE) VALUES('Batman 2','2001','8.6');
INSERT INTO SHOW_ENTITY (TITLE, YEAR, IMDB_SCORE) VALUES('Hulk','2010','5.4');
